import pymysql
import os
from dotenv import load_dotenv
from urllib.parse import urlparse

load_dotenv()

def cleanup_schema():
    db_url = os.environ.get('DATABASE_URL', '')
    p = urlparse(db_url.replace('mysql+pymysql://', 'http://'))
    
    connection = pymysql.connect(
        host=p.hostname,
        user=p.username,
        password=p.password,
        port=p.port or 3306,
        database=p.path.lstrip('/'),
        charset='utf8mb4'
    )
    
    cursor = connection.cursor()
    
    # List of tables to DROP (the singular ones generated by default)
    tables_to_drop = [
        'user', 'trade', 'course', 'module', 'lesson', 'quiz', 
        'user_challenge', 'payment', 'chat_message', 'user_progress',
        'certificate', 'quiz_answer'
    ]
    
    print("[CLEANUP] Cleaning up duplicate tables...")
    cursor.execute("SET FOREIGN_KEY_CHECKS = 0")
    
    for table in tables_to_drop:
        try:
            cursor.execute(f"DROP TABLE IF EXISTS {table}")
            print(f"   Dropped {table}")
        except Exception as e:
            print(f"   Error dropping {table}: {e}")
            
    cursor.execute("SET FOREIGN_KEY_CHECKS = 1")
    connection.commit()
    connection.close()
    print("✅ Schema cleanup complete.")

if __name__ == "__main__":
    cleanup_schema()
